version: "3.8"

services:
    mysqldb:
        image:  mysql:latest
        container_name: mysqldb
        hostname: mysqldb
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: mission_control
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - back-tier
    server:
        build: server/
        command: bash -c "sleep 20s; alembic upgrade head; uvicorn src.main:app --host 0.0.0.0 --port 9000 --reload"
        volumes:
            - ./server/src:/server/src
        ports:
            - 9000:9000
        expose:
            - 9000
        networks:
            - back-tier
        depends_on:
            - mysqldb
        environment:
            DATABASE_URL: mysql+pymysql://root:root_password@mysqldb:3306/mission_control

    client:
        build: client/
        volumes:
            - ./client/src:/client/src
            - ./client/vite.config.ts:/client/vite.config.ts
        ports:
            - 3000
        networks:
            - back-tier
        links:
            - server

    proxy:
        image: nginx:stable-alpine
        ports:
            - 8080:8080
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - front-tier
            - back-tier
        links:
            - client
            - server
        depends_on:
            - mysqldb
            - client
            - server
volumes:
    mysql_data:
networks:
    front-tier:
        attachable: true
    back-tier: {}

